---
apiVersion: v1
kind: ConfigMap
metadata:
  name: motd-configmap
data:
  listen_port: '5555'
  message_content: 'Hello World!'
  default.conf.template: |
    server {
      listen  0.0.0.0:${APP_PORT};
      listen  [::]:${APP_PORT};
      server_name  localhost;

      location / {
          access_log off;
          default_type application/json;
          return 200 '{"message": "${MESSAGE}"}';
      }
    }
